const GameActionTypes = {
  PREPARE_GAME: "PREPARE_GAME",
  END_GAME: "END_GAME",
  UPDATE_SCORE: "UPDATE_SCORE",
  UPDATE_TIME_REMAINING: "UPDATE_TIME_REMAINING",
  UPDATE_CLICK_COUNT: "UPDATE_CLICK_COUNT",
  UPDATE_FINAL_SCORE: "UPDATE_FINAL_SCORE",
  TIME_UP: "TIME_UP",
};

export default GameActionTypes;
