export const _EMOTICONS_COLLECTION = {
  Grape: ["em em-grapes", "GRAPES"],
  Red_Apple: ["em em-apple", "RED APPLE"],
  Wild_Cherry: ["em em-cherries", "CHERRIES"],
  Lemonade: ["em em-lemon", "LEMON"],
  Pineapple: ["em em-pineapple", "PINEAPPLE"],
  Strawberry: ["em em-strawberry", "STRAWBERRY"],
  Kiwi: ["em em-kiwifruit", "KIWIFRUIT"],
  Cheeseburger: ["em em-hamburger", "HAMBURGER"],
  Tangerine: ["em em-tangerine", "TANGERINE"],
  Popcorn: ["em em-popcorn", "POPCORN"],
  Lollipop: ["em em-lollipop", "LOLLIPOP"],
  Chocolate: ["em em-chocolate_bar", "CHOCOLATE BAR"],
  Curry_and_Rice: ["em em-curry", "CURRY AND RICE"],
  Pizza: ["em em-pizza", "SLICE OF PIZZA"],
  Smoothie: ["em em-cup_with_straw", "CUP WITH STRAW"],
  Wine: ["em em-wine_glass", "WINE GLASS"],
  Mountain: ["em em-mountain", "MOUNTAIN"],
  Snow_Capped_Mountain: ["em em-snow_capped_mountain", "Snow Capped Mountain"],
  Volcano: ["em em-volcano", "VOLCANO"],
  Campsite: ["em em-camping", "CAMPING"],
  Beach_With_Umbrella: ["em em-beach_with_umbrella", "Beach With Umbrella"],
  Desert: ["em em-desert_island", "Desert Islnd"],
  Sport_Stadium: ["em em-stadium", "Sport Stadium"],
  Tokyo_Tower: ["em em-tokyo_tower", "TOKYO TOWER"],
  European_Castle: ["em em-european_castle", "EUROPEAN CASTLE"],
  Japanese_Castle: ["em em-japanese_castle", "JAPANESE CASTLE"],
  Mushroom: ["em em-mushroom", "MUSHROOM"],
  Petrol_Pump: ["em em-fuelpump", "FUEL PUMP"],
  Railway_Track: ["em em-railway_track", "Railway Track"],
  Railway_Locomotive: ["em em-steam_locomotive", "STEAM LOCOMOTIVE"],
  Ambulance: ["em em-ambulance", "AMBULANCE"],
  Fire_Truck: ["em em-fire_engine", "FIRE ENGINE"],
  Space_Shuttle: ["em em-rocket", "ROCKET"],
  Helicopter: ["em em-helicopter", "HELICOPTER"],
  Speed_Boat: ["em em-speedboat", "SPEEDBOAT"],
  Plane: ["em em-airplane_arriving", "AIRPLANE ARRIVING"],
  Skier: ["em em-skier", "Skier"],
  Snowboarding: ["em em-bird", "BIRD"],
  Circus: ["em em-circus_tent", "CIRCUS TENT"],
  Cricket: ["em em-cricket_bat_and_ball", "CRICKET BAT AND BALL"],
  Bowling_Ball: ["em em-bowling", "BOWLING"],
  Table_Tennis: [
    "em em-table_tennis_paddle_and_ball",
    "TABLE TENNIS PADDLE AND BALL",
  ],
  Tent: ["em em-tent", "TENT"],
  Badminton_Racquet_and_Shuttlecock: [
    "em em-badminton_racquet_and_shuttlecock",
    "BADMINTON RACQUET AND SHUTTLECOCK",
  ],
  Electric_Guitar: ["em em-guitar", "GUITAR"],
  Postbox: ["em em-postbox", "POSTBOX"],
  Magnet: ["em em-magnet", "MAGNET"],
  Avocado: ["em em-avocado", "AVOCADO"],
  Bike: ["em em-bike", "BICYCLE"],
  Fire_Extinguisher: ["em em-fire_extinguisher", "FIRE EXTINGUISHER"],
  Candle: ["em em-candle", "Candle"],
  Candy: ["em em-candy", "CANDY"],
  Clover: ["em em-four_leaf_clover", "FOUR LEAF CLOVER"],
  Maple: ["em em-maple_leaf", "MAPLE LEAF"],
  Mango: ["em em-mango", "MANGO"],
  Tulip: ["em em-tulip", "TULIP"],
  Rose: ["em em-rose", "ROSE"],
  Rooster: ["em em-rooster", "ROOSTER"],
  Fish: ["em em-tropical_fish", "TROPICAL FISH"],
  Telescope: ["em em-telescope", "TELESCOPE"],
  Christmas: ["em em-christmas_tree", "CHRISTMAS TREE"],
  Cookie: ["em em-cookie", "COOKIE"],
  Omelette: ["em em-fried_egg", "COOKING"],
  Soccer: ["em em-soccer", "SOCCER BALL"],
  Violin: ["em em-violin", "VIOLIN"],
  Telephone: ["em em-phone", "BLACK TELEPHONE"],
};
